CREATE DATABASE IF NOT EXISTS WEB_VONG_TAY;
USE WEB_VONG_TAY;
CREATE TABLE IF NOT EXISTS SAN_PHAM(
	MA INT NOT NULL AUTO_INCREMENT,
    TEN VARCHAR(255) NOT NULL,
    MOTA VARCHAR(255),
    GIA INT NOT NULL,
    SO_LUONG_CON INT NOT NULL DEFAULT 0,
    SO_LUONG_DA_BAN INT NOT NULL DEFAULT 0,
    PRIMARY KEY(MA)
);

CREATE TABLE IF NOT EXISTS HINH_ANH(
	MA INT NOT NULL AUTO_INCREMENT,
    URL VARCHAR(255),
    PRIMARY KEY(MA)
);

CREATE TABLE IF NOT EXISTS SAN_PHAM_HINH_ANH(
	MA_SAN_PHAM INT NOT NULL,
    MA_HINH_ANH INT NOT NULL,
    MOTA VARCHAR (255),
    PRIMARY KEY(MA_SAN_PHAM, MA_HINH_ANH)
);
ALTER TABLE SAN_PHAM_HINH_ANH
	ADD FOREIGN KEY(MA_SAN_PHAM) REFERENCES SAN_PHAM(MA),
    ADD FOREIGN KEY(MA_HINH_ANH) REFERENCES HINH_ANH(MA);
    
CREATE TABLE IF NOT EXISTS HOA_DON(
	MA INT NOT NULL AUTO_INCREMENT,
    TONG_TIEN_HOA_DON INT NOT NULL,
    TONG_TIEN_SAU_CUNG INT NOT NULL,
    MA_GIAM_GIA INT,
    NGAY DATETIME NOT NULL DEFAULT NOW(),
    DIA_CHI VARCHAR(255) NOT NULL,
    SO_DIEN_THOAI VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    TEN_KHACH_HANG VARCHAR(255) NOT NULL,
    TINH_TRANG VARCHAR(255) NOT NULL DEFAULT 'DANG XU LY',
    HINH_THUC_THANH_TOAN VARCHAR(255) NOT NULL DEFAULT 'TIEN MAT',
    PRIMARY KEY(MA)
);

CREATE TABLE IF NOT EXISTS CHI_TIET_HOA_DON(
	MA_HOA_DON INT NOT NULL,
	MA_SAN_PHAM INT NOT NULL,
    SO_LUONG INT NOT NULL,
    GIA INT NOT NULL,
    GIAM_GIA INT NOT NULL DEFAULT 0,
    MA_GIAM_GIA INT NOT NULL,
    PRIMARY KEY(MA_HOA_DON, MA_SAN_PHAM)
);
ALTER TABLE CHI_TIET_HOA_DON
	ADD FOREIGN KEY(MA_HOA_DON) REFERENCES HOA_DON(MA),
    ADD FOREIGN KEY(MA_SAN_PHAM) REFERENCES SAN_PHAM(MA);
    
CREATE TABLE IF NOT EXISTS ADMINS(
	USERNAME VARCHAR(255) NOT NULL,
    PASSWD VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERNAME)
);



